language: php

services:
  - redis-server

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install
  - php artisan route:list
  - phpunit

script:
  - php artisan key:generate
